chore: Log In
atlp-rwanda/rca-phantom-team1-bn pull request #13
Opened 2023-03-21 09:03 UTC by SauveJeanLuc

# Add login functionality for driver and operator roles

## Description

This pull request implements the login feature for all roles. It adds a login form with validation and error handling, authentication logic using JWT and bcrypt.

## How to test

- Run `npm install` to install the dependencies
- Run `npm run dev` to start the development server
- Navigate to `http://localhost:{PORT}/api-docs` for swagger documentation and head to Auth on auth/login endpoint.
-  Enter the credentials provided by the operator or administrator
- Verify that you can log in successfully and access the tasks assigned to your role
- Verify that you cannot log in with invalid credentials or access tasks that are not authorized for your role

## Screenshots

![image](https://user-images.githubusercontent.com/68426990/226558472-ad2e6713-a52e-41c2-8665-3ef91d856288.png)
![image](https://user-images.githubusercontent.com/68426990/226558372-5c32773a-a732-46d0-8765-8c150a10596e.png)

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have added comments and documentation where necessary
- [x] I have followed the coding standards and style guidelines

2023-03-21 09:08 UTC, PatrickNiyogitare28 reviewed
LGTM though tests are still missing for this work.

2023-03-21 09:45 UTC, TuyizeeAnastase requested changes

2023-03-21 09:45 UTC, TuyizeeAnastase commented on src/db/models/user.js
> +      role: {
the role is integer, not string name it as `role_id:integer`

2023-03-21 09:45 UTC, TuyizeeAnastase commented on src/api/validations/auth.validator.js
> +    password: Joi.string().required(),
validate password length check `max` function

2023-03-21 09:45 UTC, TuyizeeAnastase commented on src/api/controllers/auth.controller.js
> +    const user = await models.user.findOne({ where: { email } }); // find the user by email
create services folder where we can add all of functions to access database

2023-03-21 09:45 UTC, TuyizeeAnastase commented on src/api/controllers/auth.controller.js
> +
add middleware to check if user exist

2023-03-22 14:38 UTC, SauveJeanLuc commented on src/db/models/user.js
> +      role: {
Done.

2023-03-22 14:38 UTC, SauveJeanLuc commented on src/api/validations/auth.validator.js
> +    password: Joi.string().required(),
Done.

2023-03-22 14:38 UTC, SauveJeanLuc commented on src/api/controllers/auth.controller.js
> +    const user = await models.user.findOne({ where: { email } }); // find the user by email
Done.

2023-03-22 14:38 UTC, SauveJeanLuc commented on src/api/controllers/auth.controller.js
> +
Done.

2023-03-23 19:39 UTC, PatrickNiyogitare28 reviewed
I can see your tests are failing on github due to failure to recognize DB environments. Can you please check in my branch `/github/workflows/ci-cd.yml` There is one line you need to add to get that fixed.

2023-03-24 09:51 UTC, ernesteNtezirizaza approved these changes

2023-03-28 10:58 UTC, PatrickNiyogitare28 approved these changes

2023-03-28 13:47 UTC, TuyizeeAnastase approved these changes

2023-03-28 13:48 UTC, merged