Allow drivers and operators to update their own profiles
atlp-rwanda/rca-phantom-team1-bn pull request #14
Opened 2023-03-22 18:54 UTC by Cyebukayire

### **Description**

This pull request implements the update profile feature for drivers and operators. 

### **How to test**
Run `npm install ` to install the dependencies
Run `npm run db:reseed` to use default registered users
Run `npm run dev` to start the development server
Navigate to http://localhost:{PORT}/api-docs for swagger documentation and head to Profile on `/api/profile/` endpoint.
Enter the body data using format of the default example provided 

Remember to use `1` as your `id` parameter for a successful profile update (Since the login feature is not yet merged to the develop branch we are hard coding a logged in use to have `user id = 1`)

### **Screenshot**
![image](https://user-images.githubusercontent.com/55869293/227005196-517f6407-31ca-46b7-bac9-add40742242e.png)

**Result**
![image](https://user-images.githubusercontent.com/55869293/227005306-466bd897-a54c-4763-af3e-328f25e0a24c.png)

### **Checklist**

- [ ] The operator and driver are able to update information about their own profile.
- [ ] Appropriate error messages are displayed on unsuccessful attempts.
- [ ] Created `src/utils/responseHandler` to help handle success and failure responses without repeating the same codes for every API. 

### Note!
Very necessary issues that occurred on the database side (Couldn't run `db:migrate` and anything else related to migrations) were resolved by @PatrickNiyogitare28 on this [PR](https://github.com/atlp-rwanda/rca-phantom-team1-bn/pull/10). So I had to pull his work to be able to use the database even though the PR is not yet merged.

 ### **Changes Required**

- Since this feature is depending on the login feature that is not yet merged, I had to hard-code logged in user in `src/api/controller/profile.controller.js` which will be changed latter.
- The routes also are not protected; a middle ware to check athaurization and verify the user is expected later which is not part of this PR.

2023-03-23 09:56 UTC, PatrickNiyogitare28 reviewed
The feature looks good to me but I think you need to write tests for it.

2023-03-23 11:28 UTC, Cyebukayire commented
> The feature looks good to me but I think you need to write tests for it.

Ohhh thank you @PatrickNiyogitare28, I should do that too

2023-03-23 19:41 UTC, PatrickNiyogitare28 commented
> > The feature looks good to me but I think you need to write tests for it.
> 
> Ohhh thank you @PatrickNiyogitare28, I should do that too

Let me know if you need an assistance with it.

2023-03-24 09:48 UTC, ernesteNtezirizaza approved these changes

2023-03-29 12:16 UTC, PatrickNiyogitare28 approved these changes

2023-03-29 13:23 UTC, TuyizeeAnastase requested changes

2023-03-29 13:23 UTC, TuyizeeAnastase commented on src/api/routes/profile.routes.js
> +profileRouter.get("/:id", userProfileExists, getProfile);
get("/profile", checkIfUSerLogged,getProfile)

2023-03-29 13:23 UTC, TuyizeeAnastase commented on src/api/routes/profile.routes.js
> +);
put("/profile",checkUSerLogged,validation,updateProfile)

2023-03-30 15:03 UTC, merged