Feat/buses crud
atlp-rwanda/rca-phantom-team1-bn pull request #15
Opened 2023-03-27 13:38 UTC by IrakozeLoraine

## What does this PR do
- It implements the bus feature
- It adds the feature tests

## Description
- Operator is able to perform the CRUD operations on buses
- Buses can be seeded at once for development purposes by running `npm run db:seeds`

## How to manually test this 
- Check in the branch `feat/buses-crud`
- Run the server
- Open the Swagger API documentation to test the buses

## Relevant Trello story 
[11-crud-operations-for-buses][(https://trello.com/c/a6wcZ3PE/9-create-roles-and-set-permissions)](https://trello.com/c/maUQgDhP/11-crud-operations-for-buses)

## Screenshots
![image](https://user-images.githubusercontent.com/53254885/227944406-db62114f-9ac7-4c8e-bad3-2dc9f7ff8317.png)

![image](https://user-images.githubusercontent.com/53254885/227944593-bc36c327-a893-4eb3-8f93-48a0f75cd073.png)

2023-03-27 15:03 UTC, TuyizeeAnastase requested changes

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/controllers/bus.controllers.js
> +
add middleware which check this, check if bus exist by id

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/controllers/bus.controllers.js
> +        if (!bus) {
use above option using middleware to check if bus exist by id

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/controllers/bus.controllers.js
> +        res.status(StatusCodes.OK).json({
the same like above add middleware to check if bus exist by id

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/services/bus.service.js
> +};
add pagination to get All buses to refer to this [pagination](https://www.bezkoder.com/node-js-sequelize-pagination-mysql/)

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/validations/bus.validate.js
> +    agency_id: Joi.string().required(),
driver_id and agency_id are not string

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/db/migrations/20230323144307-create-driver.js
> +  async down(queryInterface, Sequelize) {
we don't have a table called Driver it's User remove it,

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/db/seeders/20230323144350-Agency.js
> +'use strict';
add agencies seeding

2023-03-27 15:03 UTC, TuyizeeAnastase commented on src/api/routes/buses.routes.js
> +router.post("/", createBus)
before adding the bus add this middleware
- check if the bus is not registered by plate_number
- check if user Exists and it has driver as rols
- check if agency exist

2023-03-28 20:24 UTC, IrakozeLoraine commented on src/api/routes/buses.routes.js
> +router.post("/", createBus)
I can't create the middleware for agency until the controllers are ready.

2023-03-29 07:53 UTC, TuyizeeAnastase requested changes

2023-03-29 07:53 UTC, TuyizeeAnastase commented on src/api/controllers/bus.controllers.js
To update and delete the bus add middleware to check if the bus exists by id no need after adding that middleware
`if (!bus) {
            return res.status(StatusCodes.NOT_FOUND).json({
                success: false,
                message: locales('bus_not_found'),
            });
        }`

2023-03-29 07:53 UTC, TuyizeeAnastase commented on src/api/routes/buses.routes.js
> +router.post("/", checkUserLoggedIn, restrictTo(ERoles.OPERATOR), busExistsByPlateNumber, createBus)
add middleware to check if agency exist by agency_id

2023-03-29 12:24 UTC, thepatrickniyo reviewed
There is an error in migration associations. Pull the latest version on develop then if you have time we look into it.

2023-03-29 12:50 UTC, SauveJeanLuc commented
resolve conflicts

2023-03-30 11:42 UTC, thepatrickniyo approved these changes

2023-03-30 20:57 UTC, ernesteNtezirizaza approved these changes

2023-03-31 09:22 UTC, TuyizeeAnastase approved these changes

2023-03-31 09:22 UTC, merged