Feat/routes crud
atlp-rwanda/rca-phantom-team1-bn pull request #16
Opened 2023-03-28 08:47 UTC by ntwari-egide

## What does this PR do

-   It shows implementation of Routes model, service, controller and routes.

## Description

- As  **an operator**, I want to create routes so that buses can travel in pre-defined routes.

- As  **an operator**, I want to create routes so that users can view in pre-defined routes.

## How to manually test this

-   Check in the branch  `feat/routes-crud`
-   Run the server
-   Open the Swagger API documentation to test the buses

## Relevant Trello story

[7-crud-operations-for-routes][(https://trello.com/c/siqznvua/7-crud-operations-for-routes)](https://trello.com/c/siqznvua/7-crud-operations-for-routes)

## Screenshots

![enter image description here](https://res.cloudinary.com/dpqasrwfu/image/upload/v1679992665/Screen_Shot_2023-03-28_at_10.35.11_zqoawu.png)

2023-03-28 10:08 UTC, TuyizeeAnastase requested changes

2023-03-28 10:08 UTC, TuyizeeAnastase commented on src/api/controllers/routes.controller.js
> +}
i need you send json files [refer](https://github.com/atlp-rwanda/rca-phantom-team1-bn/pull/10/files#diff-259e2aeb7411d1bdb2045e475b436e668eff745d5fe360df7bd5274d1c927091) to this

2023-03-28 10:08 UTC, TuyizeeAnastase commented on src/api/routes/routes.routes.js
> +
add middleware to check if route exist by `id`  before editing or deleting

2023-03-28 10:08 UTC, TuyizeeAnastase commented on src/api/routes/routes.routes.js
> +
add middleware to check if route with that id exist

2023-03-28 10:08 UTC, TuyizeeAnastase commented on src/api/routes/routes.routes.js
> +/**
- middleware to validate user input  check [this ](https://github.com/atlp-rwanda/rca-phantom-team1-bn/pull/10/files#diff-c62c99e58d96d62ea668b8e8477a2c1272ad5e2f946a31cf98e7bf4c9f647669)
- add middleware to check if router not already exist

2023-03-28 10:08 UTC, TuyizeeAnastase commented on src/index.js
> +app.use("/routes", routesRouter);
add permissions only for operator ask Patrick for assistince

2023-03-29 12:27 UTC, PatrickNiyogitare28 reviewed
There is an error in installing dependencies as  I can see on GitHub actions. The error is possibly due to collapsed `package-lock.json` or a library with an issue, you installed. 
If you have time we can look into it.

2023-04-03 13:55 UTC, closed without merging