Chore do registration
atlp-rwanda/rca-phantom-team1-bn pull request #17
Opened 2023-03-28 09:13 UTC by Ange-Constance

**What does this PR do**
This pull requests implementation of registering new drivers and operators.

### **Description**

1. The administrator should be able to register a new driver or a new operator.
2. An email containing a random password should be sent to the provider email.
3. The driver or operator should be able to sign in to the app using their email and the provided password.
4.Appropriate error messages are displayed on unsuccessful attempts.

### **How to manually test this**

1. Check in the branch chore-do-registration
2. Run the server
3. Open the Swagger API documentation to test driver & operators

### **Relevant Trello story**
[10-register-drivers-operators][(https://trello.com/c/SDfWF0QF/10-register-drivers-operators)](https://trello.com/c/SDfWF0QF/10-register-drivers-operators)

### **Screenshots** 

![result](https://user-images.githubusercontent.com/54369909/228188765-a6eed883-1686-4169-ae21-ab1dc32259c4.png)
![phantom](https://user-images.githubusercontent.com/54369909/228188781-d71647c6-2603-4f60-8f79-e6196b356d46.png)

2023-03-28 09:53 UTC, TuyizeeAnastase requested changes

2023-03-28 09:53 UTC, TuyizeeAnastase commented on src/api/routes/signup.routes.js
> + *       400:
- I want only one endpoint
- add middleware to check if a user is not already registered by email
- our request body will be like this:
![Screenshot from 2023-03-28 11-46-51](https://user-images.githubusercontent.com/42033331/228197773-64a9824d-ecc0-4e55-84fb-692cd650b574.png)

2023-03-28 09:53 UTC, TuyizeeAnastase commented on src/api/controllers/signup.controller.js
> +  });
create one controller that will receive 
- will receive that body from the postman `name,email,role(operator or driver)`
- find role By RoleTitle `const role=findOne(req.body.role) `to get role `id`
- `const newUser={name,email,password:hashedPassword,role_id:role.id}` 
- finally save newUser

2023-03-29 12:33 UTC, PatrickNiyogitare28 reviewed
There is a lint error causing the ci-cd action to fail

2023-03-30 12:01 UTC, TuyizeeAnastase approved these changes
Next time make sure, you are using naming conventions of PR descriptions refer to [this](https://github.com/atlp-rwanda/engineering-playbook/wiki)

2023-03-30 12:03 UTC, merged